services:
  - type: web
    name: caloriecurve-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: "/healthz"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        sync: false